name: sparsesurv_venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.17
  - numpy=1.23.4
  - pandas=1.5.1
  - requests=2.28.1
  - scipy=1.9.3
  - setuptools=68.0.0
  - yaml=0.2.5
  - sphinx==5.3.0
  - pip:
    - better-apidoc==0.3.2
    - celer==0.7.2
    - matplotlib==3.7.1
    - numba==0.56.4
    - pytest==7.3.1
    - scikit-learn==1.2.1
    - scikit-survival==0.20.0
    - seaborn==0.12.2
    - sklearn==0.0.post1
    - typeguard==2.13.3
