snakemake_min_version: "7.30.1"
mambaforge_version: "23.3.1-0"
config_path: "config/config.json"
datasets:
  ["BLCA", "BRCA", "HNSC", "KIRC", "LGG", "LIHC", "LUAD", "LUSC", "OV", "STAD"]
random_seed: 42
n_outer_repetitions: 25
n_outer_splits: 5
